### ISSUE TITLE
Level goes away when Dimension travelling

### ISSUE THREAD

**Issue by EmpathicPanda** [htachoires/Set-Home-Waypoints#1]
When I was in the Nether and used /home to get in my Overworld Home, my Level bar showed nothing.
As soon as I got level again, it showed my levels again.
But I couldn't enchant something.

Version 1.20.1

**Comment by htachoires** [comment]
Hello @EmpathicPanda, thank you for your feedback and sorry for what happened to you.

I will try to reproduce your bug to plan a fix

**Comment by htachoires** [comment]
Hello @EmpathicPanda, indeed levels goes away after teleporting **Nether** => **Overworld**.  However, I could enchant something after gaining some experience back.

Are you sure you had enough experience to echant your item ?

If yes, can you provide some picture of your issue ? This would help for debugging.

**Comment by htachoires** [comment]
I think this is a problem at minecraft level. I ran the command `/execute in minecraft:overworld run tp <player> ~ ~ ~` in the **Nether** to teleport the player in the **Overworld**. The level vanished again and showed up again after gaining some exeperience.

This is strange that you could not enchant your gear

**Comment by htachoires** [comment]
Minecraft level issue, this can't be resolved
